### ISSUE TITLE
Добавь gitignore

### ISSUE THREAD

**Issue by gloomweaver** [Emniz/InheritanceExample#1]
https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by Emniz** [comment]
A ne hochy

**Comment by gloomweaver** [comment]
Lokh

**Comment by Emniz** [comment]
U menya s detstva strah na gitignor

**Comment by gloomweaver** [comment]
Ladno, No mozet sluchitsa execution. So bud ready.
